from .course import idhandlers
from .course import hashtagHandlers
from .course import commandsFilter
from .course import contentHandlers
from .course import textHandlers
from .course import regexHandlers
from .course import adminHandlers
from .course import otherHandlers
from . import start
from . import help
from . import languageHandler
from . import fullNameHandler
from . import phoneNumberHandler
from . import mainMenuHandler
from . import birthDateHandler
from . import settingsHandler
from . import changeLanguageHandler
from . import changeBirthDateHandler
from . import admin
